name: No Simulator Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run Unit Tests without launching Simulator
    runs-on: macos-15
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '16.1'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          xcodebuild test -scheme NoSimulatorModelTests
